### PR TITLE
#167733640 Setup backend application to use docker

### PR DESCRIPTION
**Pull request by King-Success**
#### Description of Task to be completed?
Should ensure that docker is properly setup on this application
#### How should this be manually tested?
On the project root directory, run `docker-compose up -d` this should start a local development server with all the necessary services running on the background
#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
#167733640
#### Screenshots (if appropriate)
Screen Shot 2019-08-15 at 1 34 24 AM

### CODE REVIEW

**Comment by chis0m** [comment]
I do Okay! the PR seeing it has the basic files for the docker environment configuration. That is the dockerfile and docker-compose.yml

**Comment by daylay92** [comment]
I do not much experience with docker but it seems to work just fine on my local upon testing, however, kindly confirm that you have sorted the database connection out with @chis0m. Aside that, I think it was well done.

**Comment by emmanuelnwankwo** [comment]
My first time of using Docker, the installation is straightforward and it's working

**Comment by King-Success** [comment]
> I do not much experience with docker but it seems to work just fine on my local upon testing, however, kindly confirm that you have sorted the database connection out with @chis0m. Aside that, I think it was well done.

**Comment by King-Success** [comment]
> I do not much experience with docker but it seems to work just fine on my local upon testing, however, kindly confirm that you have sorted the database connection out with @chis0m. Aside that, I think it was well done.

@daylay92 After a bit of research, I figured that the database connection wouldn't be a problem, the database instance running on docker allows you to run the application and connect to the database (Postgres) without you needing to install Postgres database on your local machine. The application would still work exactly the same way as though you are connecting to a database on your local machine.

**Pull request closed without merging**
