### PR TITLE
#167733641 Add app.json required for Review Apps

### PR DESCRIPTION
**Pull request by daylay92**
#### What does this PR do?
Add app.json file required to ensure review Apps on **Heroku** whenever a pull request is made

#### Description of Task to be completed?
Carry out the following Tasks: 
- create app.json file
- Add app.json configuration
- Update .env.sample file

#### Any background context you want to provide?
 This activity is an important prerequisite for setting up Continuous delivery on Heroku and must be approved before I can complete deployment to Heroku according to the requirement

#### What are the relevant pivotal tracker stories?
#167733641

### CODE REVIEW

**Comment by chis0m** [comment]
This looks good, Weldone @daylay92

**Review by chis0m — COMMENTED** [review]
this looks okay

**Review by Baystef — APPROVED** [review]
Manifest file properly configured and ready to go

**Review by dchima — APPROVED** [review]
app.json seems to follow the Heroku Schema.

**Review by King-Success — APPROVED** [review]
Good job Ayo, I like the concept of review apps

**Comment by daylay92** [comment]
Thanks for your kind reviews @King-Success @Baystef @dchima

**Review by chis0m — APPROVED** [review]

**Review by Segun-Ogundipe — APPROVED** [review]
Great work!!!

**Review by dchima — APPROVED** [review]
Nicely done matching the heroku schema

**Review by King-Success — APPROVED** [review]

**Pull request merged**
